@echo off
setlocal EnableDelayedExpansion

REM ===================================================================
REM  UNIFIED STARTUP SCRIPT - Patient Monitoring System
REM  Auto-configures network and starts all services
REM ===================================================================

color 0A
title Patient Monitoring System - Unified Startup

echo.
echo ====================================================================
echo   PATIENT MONITORING SYSTEM - UNIFIED STARTUP
echo ====================================================================
echo.

REM ===================================================================
REM  STEP 1: Detect Current IP Address
REM ===================================================================

echo [1/6] Detecting network configuration...
echo.

REM Use PowerShell to detect the current IP
for /f "tokens=*" %%i in ('powershell -Command "Try { $ip = (Get-NetIPAddress -AddressFamily IPv4 | Where-Object { $_.IPAddress -notlike '127.*' -and $_.PrefixOrigin -eq 'Dhcp' } | Select-Object -First 1).IPAddress; if ($ip) { Write-Output $ip } else { Write-Output 'localhost' } } Catch { Write-Output 'localhost' }"') do set DETECTED_IP=%%i

echo    Detected IP: %DETECTED_IP%
echo.

REM ===================================================================
REM  STEP 2: Generate Frontend .env File
REM ===================================================================

echo [2/6] Generating frontend configuration...
echo.

set FRONTEND_DIR=%~dp0frontend_new
set ENV_FILE=%FRONTEND_DIR%\.env

if not exist "%FRONTEND_DIR%" (
    echo    ERROR: Frontend directory not found: %FRONTEND_DIR%
    pause
    exit /b 1
)

REM Create .env file with detected IP
(
    echo # Backend API Configuration
    echo # Auto-generated by START_ALL.bat on %date% at %time%
    echo # Current IP: %DETECTED_IP%
    echo.
    echo VITE_API_URL=http://%DETECTED_IP%:8000
    echo VITE_WS_URL=ws://%DETECTED_IP%:8000
) > "%ENV_FILE%"

echo    Created: frontend_new\.env
echo    API URL: http://%DETECTED_IP%:8000
echo.

REM ===================================================================
REM  STEP 3: Check Dependencies
REM ===================================================================

echo [3/6] Checking dependencies...
echo.

REM Check Python
python --version >nul 2>&1
if errorlevel 1 (
    echo    ERROR: Python is not installed or not in PATH
    echo    Please install Python 3.8+ from python.org
    pause
    exit /b 1
)
echo    ✓ Python found

REM Check Node.js
node --version >nul 2>&1
if errorlevel 1 (
    echo    ERROR: Node.js is not installed or not in PATH
    echo    Please install Node.js from nodejs.org
    pause
    exit /b 1
)
echo    ✓ Node.js found

REM Check npm
npm --version >nul 2>&1
if errorlevel 1 (
    echo    ERROR: npm is not installed or not in PATH
    pause
    exit /b 1
)
echo    ✓ npm found

echo.

REM ===================================================================
REM  STEP 4: Install Python Dependencies (if needed)
REM ===================================================================

echo [4/6] Checking Python dependencies...
echo.

set BACKEND_DIR=%~dp0backend
cd /d "%BACKEND_DIR%"

if not exist "requirements.txt" (
    echo    WARNING: requirements.txt not found
) else (
    echo    Installing/updating Python packages...
    pip install -q -r requirements.txt
    if errorlevel 1 (
        echo    WARNING: Some Python packages may not have installed correctly
    ) else (
        echo    ✓ Python packages ready
    )
)

echo.

REM ===================================================================
REM  STEP 5: Install Frontend Dependencies (if needed)
REM ===================================================================

echo [5/6] Checking frontend dependencies...
echo.

cd /d "%FRONTEND_DIR%"

if not exist "node_modules" (
    echo    Installing npm packages (this may take a few minutes)...
    call npm install
    if errorlevel 1 (
        echo    ERROR: Failed to install npm packages
        pause
        exit /b 1
    )
) else (
    echo    ✓ npm packages already installed
)

echo.

REM ===================================================================
REM  STEP 6: Start Services
REM ===================================================================

echo [6/6] Starting services...
echo.

REM Start backend in new window
cd /d "%BACKEND_DIR%"
start "Backend Server" cmd /k "python main.py"

echo    ✓ Backend starting in separate window...
echo      Please wait for QR code to appear in backend window
echo.

REM Wait for backend to start
echo    Waiting 5 seconds for backend to initialize...
timeout /t 5 /nobreak >nul

REM Start frontend in new window
cd /d "%FRONTEND_DIR%"
start "Frontend Development Server" cmd /k "npm run dev"

echo    ✓ Frontend starting in separate window...
echo.

REM ===================================================================
REM  CONNECTION INFORMATION
REM ===================================================================

echo ====================================================================
echo   SERVICES STARTED SUCCESSFULLY!
echo ====================================================================
echo.
echo   Backend Server:
echo      Local:   http://localhost:8000
echo      Network: http://%DETECTED_IP%:8000
echo      Docs:    http://%DETECTED_IP%:8000/docs
echo.
echo   Frontend Application:
echo      Local:   http://localhost:3000
echo      (Check Frontend window for exact port)
echo.
echo   Mobile App Setup:
echo      1. Open the Nurse Alarm App
echo      2. Tap the menu icon (☰) → Settings
echo      3. Navigate to "Network Settings"
echo      4. Scan the QR code from Backend window OR
echo      5. Manually enter: http://%DETECTED_IP%:8000
echo.
echo ====================================================================
echo   IMPORTANT NOTES:
echo ====================================================================
echo.
echo   • QR Code for mobile app is displayed in the Backend window
echo   • Both Backend and Frontend windows will remain open
echo   • Close those windows to stop the servers
echo   • Your IP: %DETECTED_IP% (may change if network changes)
echo.
echo   If your IP changes (WiFi switch, etc.):
echo      Run UPDATE_NETWORK.bat to reconfigure
echo.
echo ====================================================================
echo.

echo Press any key to exit this window (servers will continue running)...
pause >nul

exit /b 0
